name: CI Pipeline
on:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters
        run: |
          pip install flake8
          flake8 . --max-line-length=88 --extend-ignore=E203

      - name: Run tests
        run: python -m pytest --verbose
